/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ryabko' at '1/21/17 6:00 PM' with Gradle 2.4
 *
 * @author ryabko, @date 1/21/17 6:00 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
